name: Deploying to Github Pages
on:
  push:
    branches:
      - "main"

jobs:
  #Creating Build Job
  build:
    name: Build and test
    runs-on: ubuntu_latest

    strategy:
      matrix:
        node-version: [14]

    steps:
      name: checkout
      uses: actions/checkout@v1

      name: Install Dependencies
      run: npm ci

      name: Build
      run: npm run build:ci

      name: Test
      run: npm run test:ci

      #Upload Artifacts
      name: Archive build
      if: success()
      uses: actions/upload-artifact@v1
      with:
        name: deploy_dist
        path: dist
      
      name: Archive code coverage result
      if: success()
      uses: actions/upload-artifact@v1
      with:
        name: deploy_coverage
        path: coverage

  #Creating Deploy Job
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      name: Checkout
      uses: actions/checkout@v1
      
      name: Download Build
      uses: actions/upload-artifact@v1
      with:
        name: deploy_dist
      
      name: Deploy to Github Pages
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: deploy-dist/json-placeholder